version: "3.7"

services:
  web:
    depends_on:
      db:
        condition: service_healthy
    networks:
      - praksislista_network

  db:
    image: mysql
    #Taken from https://stackoverflow.com/questions/42567475/docker-compose-check-if-mysql-connection-is-ready
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - praksislista_network

  proxy:
    image: caddy:2.7
    restart: unless-stopped
    environment:
      WEBPORT: 3000
      DOMAIN: ${DOMAIN:-localhost}
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019"
    networks:
      - praksislista_network
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  praksislista_network:
