version: "3.7"
services:
  dev_server:
    build:
      context: .
      target: dev
    profiles:
      - dev
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      prisma_browser:
        condition: service_started
    ports:
      - 3000:3000

  prisma_browser:
    build:
      context: .
      target: prismaBrowser
    profiles:
      - dev
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5555:5555
  
  prod_server:
    build:
      context: .
      target: release
    profiles:
      - prod
    depends_on:
      - db
    ports:
      - 3000:8080

  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=praksislista
      - MYSQL_ROOT_PASSWORD=changeme
    profiles: ["dev", "prod", "db"]
    #Taken from https://stackoverflow.com/questions/42567475/docker-compose-check-if-mysql-connection-is-ready
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    ports:
      - 3306:3306