version: "3.7"
include:
  - docker-compose.common.yaml
services:
  web:
    build:
      context: .
      target: prod
  db:
    environment:
      - MYSQL_DATABASE=praksislista
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
